mariadb:
  global:
    defaultStorageClass: "nfs-csi-k8s"
  architecture: "standalone"
  auth:
    database: "golist"
    username: "golist"
    password: "golist"
  image:
    registry: "docker.io"
    repository: "bitnami/mariadb"
    tag: "latest"
  primary:
    persistence:
      enabled: true
      storageClass: "nfs-csi-k8s"
